# cloudbuild.yaml (리포지토리 루트에 놓고,
# 트리거는 “Build configuration”을 cloudbuild.yaml 으로 지정하세요)

# 1) 도커 이미지를 Artifact Registry에 빌드·푸시
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
          'build',
          '-t', 'us-central1-docker.pkg.dev/hyperscale-ai-442809/esg-rag-agent/fastapi-rag-app:$SHORT_SHA',
          '.'
      ]

images:
  - 'us-central1-docker.pkg.dev/hyperscale-ai-442809/esg-rag-agent/fastapi-rag-app:$SHORT_SHA'

  # 2) gcloud run deploy 단계
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud beta run deploy esg-rag-app \
          --image=us-central1-docker.pkg.dev/hyperscale-ai-442809/esg-rag-agent/fastapi-rag-app:$SHORT_SHA \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --service-account=439283128936-compute@developer.gserviceaccount.com \
          --vpc-connector=esg-agent-vpc-connector \
          --vpc-egress=private-ranges-only \
          --add-cloudsql-instances=hyperscale-ai-442809:us-central1:chat-db-instance \
          --set-env-vars=\
  DATABASE_URL=postgresql://postgres:mypassword@10.30.0.3:5432/chatdb,\
  ALLOYDB_URL=postgresql://postgres:1q2w3e4r5t@10.20.0.2:5432/postgres,\
  LANGCHAIN_TRACING_V2=true,\
  LANGCHAIN_ENDPOINT=https://api.smith.langchain.com,\
  LANGCHAIN_API_KEY=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,\
  LANGCHAIN_PROJECT=gemini \
  --port=8080
